### ISSUE TITLE
Move to official jTrack repository

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSUWP-Plugin-Analytics#13]
* [x] Use `repo.wsu.edu/jtrack/1.x.x/jtrack.min.js` and assorted files now that the other repo is deploying.
* [x] Remove current tracker code handling global and site specific IDs.
* [x] Transition to format offered by jTrack to track global and site specific IDs.

**Comment by jeremyBass** [comment]
So a side not to this is that a mix of things are able to be done now, where you can set all the options by account (eg: autolinkers to metrics) and also events all on a specific account code.  Basically an option for which account has what is what is needed.  I know we talked about this, but thought i'd log it here too.

**Comment by jeremyfelt** [comment]
Yup, we can break those out into new issues once things are in place. See #14 and #15 for next steps after this is finished.

**Comment by jeremyfelt** [comment]
This has been done for a bit now. https://github.com/washingtonstateuniversity/WSUWP-Plugin-Analytics/releases/tag/0.4.0
