### ISSUE TITLE
External links and campaign parameters

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSUWP-Plugin-Analytics#20]
Campaign parameters are being added to all external links right now and causing errors in some cases. Can we remove campaign parameters from all non-wsu links?

**Comment by jeremyBass** [comment]
just change the `outbound` rule you have to campaign false and that will do it.

**Comment by jeremyfelt** [comment]
Cool, I couldn't remember if there was a reason why it was enabled to begin with.
