### ISSUE TITLE
Network wide tracking code

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSUWP-Plugin-Analytics#27]

**Comment by jeremyBass** [comment]
It's already there, 
https://github.com/washingtonstateuniversity/WSUWP-Plugin-Analytics/blob/master/wsu-analytics.php#L418

**Comment by jeremyfelt** [comment]
We have global and platform wide, not network.

**Comment by jeremyBass** [comment]
I get what you mean, just add a dimension would be the best I would think to the platform?  We don't want to have to many codes going at the same time is way.

**Comment by jeremyfelt** [comment]
I don't think it will be used too often, but we need a way for colleges (and labs) to easily track their collection of sites separate from general platform analytics.

**Comment by jeremyBass** [comment]
Rockin, well as long as there is good need then it is what it is and will be what it will be..

**Comment by jeremyfelt** [comment]
Closing in favor of #15, which would cover this scenario and others.
